import { chromium } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
const browser = await chromium.launch({ channel: 'chrome', headless: true });
await mkdir('test-results', {recursive:true});
const page = await browser.newPage({viewport:{width:1440,height:1100}});
const errors=[];
page.on('pageerror',e=>errors.push(e.message));
page.on('console',m=>{if(m.type()==='error') errors.push(m.text())});
await page.goto('http://127.0.0.1:5173/');
await page.screenshot({path:'test-results/desktop-closed.png',fullPage:true});
await page.locator('#view-back').click();
await page.waitForTimeout(900);
await page.screenshot({path:'test-results/desktop-back.png',fullPage:true});
await page.locator('#view-front').click();
await page.locator('#fold').fill('100');
await page.waitForTimeout(1000);
await page.screenshot({path:'test-results/desktop-open.png',fullPage:true});
await page.setViewportSize({width:320,height:740});
await page.locator('[data-font="large"]').click();
await page.screenshot({path:'test-results/mobile-open.png',fullPage:true});
await page.locator('#fold').fill('4');
await page.waitForTimeout(900);
await page.screenshot({path:'test-results/mobile-closed.png',fullPage:true});
console.log(JSON.stringify({errors}));
await browser.close();
